import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import { MuteProvider } from "@/contexts/MuteProvider";
import { NotesProvider } from "@/contexts/NotesContext";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-100 dark:bg-neutral-900 h-screen`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider>
            <MuteProvider>
              <NotesProvider>
                <AppSidebar />
                <main className="flex-1 p-2 pl-0">{children}</main>
              </NotesProvider>
            </MuteProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
